name: SSH-TEST
on: push

jobs:
    build:
        name: Greeting
        runs-on: ubuntu-latest
        steps:
            - name: making ssh keys
              run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: test ssh
              run: ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kyagi@35.197.55.117 ’echo test > /home/kyagi/project/actionstest/actions.log’
