name: SSH-TEST
on: push

jobs:
    build:
        name: ssh test
        runs-on: ubuntu-latest
        steps:
            - name: making ssh config
              run: echo "$SSH_CONFIG" > ssh_config && chmod 600 key
              env:
                SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
            - name: making proxy ssh key
              run: echo "$PROXY_SSH_PRIVATE_KEY" > kyagi_id_rsa_nopass && chmod 600 key
              env:
                PROXY_SSH_PRIVATE_KEY: ${{ secrets.PROXY_SSH_PRIVATE_KEY }}
            - name: making uk ssh key
              run: echo "$UK_SSH_PRIVATE_KEY" > kyagi_id_rsa_nopass && chmod 600 key
              env:
                UK_SSH_PRIVATE_KEY: ${{ secrets.UK_SSH_PRIVATE_KEY }}
            - name: test ssh
              run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $SERVER_NAME "touch /home/universal/kyagi/testfromgit.log"
              env:
                SERVER_NAME: ${{ secrets.DEPLOY_SERVER }}
