name: SSH-FOR-UKENV
on: push

jobs:
    build:
        name: ssh test for proxy ssh
        runs-on: ubuntu-latest
        steps:
            - name: making proxy ssh key
              run: echo "$PROXY_SSH_PRIVATE_KEY" > kyagi_id_rsa_nopass && chmod 600 kyagi_id_rsa_nopass
              env:
                PROXY_SSH_PRIVATE_KEY: ${{ secrets.PROXY_SSH_PRIVATE_KEY }}
            - name: test ssh
              #run: ssh -vvv -i kyagi_id_rsa_nopass -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no universal@proxy1.ukw.jp 'ssh -i ~/.ssh/id_rsa_nopass universal@dev73.ukw.jp "hostname"'
              run: ssh -i kyagi_id_rsa_nopass -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kyagi@proxy1.ukw.jp 'hostname'
