name: SSH-FOR-UKENV
on: push

jobs:
    build:
        name: ssh test for proxy ssh
        runs-on: ubuntu-latest
        steps:
            - name: making proxy ssh key
              run: echo "$PROXY_SSH_PRIVATE_KEY" > secret && chmod 600 secret
              env:
                PROXY_SSH_PRIVATE_KEY: ${{ secrets.PROXY_SSH_PRIVATE_KEY }}
            - name: print directory
              run: ls
            - name: print directory detail
              run: pwd
#            - name: test ssh
#              run: ssh -i secret -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no kyagi@proxy1.ukw.jp 'ssh -i ~/.ssh/id_rsa_nopass universal@dev73.ukw.jp "hostname"'
