name: SSH-FOR-UKENV
on: push

jobs:
    build:
        name: ssh test for ukenv
        runs-on: ubuntu-latest
        steps:
            - name: making ssh config
              run: echo "$SSH_CONFIG" > ssh_config && chmod 600 ssh_config
              env:
                SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
            - name: making proxy ssh key
              run: echo "$PROXY_SSH_PRIVATE_KEY" > kyagi_id_rsa_nopass && chmod 600 kyagi_id_rsa_nopass
              env:
                PROXY_SSH_PRIVATE_KEY: ${{ secrets.PROXY_SSH_PRIVATE_KEY }}
            - name: making uk ssh key
              run: echo "$UK_SSH_PRIVATE_KEY" > uk_id_rsa_nopass && chmod 600 uk_id_rsa_nopass
              env:
                UK_SSH_PRIVATE_KEY: ${{ secrets.UK_SSH_PRIVATE_KEY }}
            - name: test ssh
              run: ssh -vvv -1 -F ssh_config -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $SERVER_NAME "touch /home/universal/kyagi/testfromgit.log"
              env:
                SERVER_NAME: ${{ secrets.DEPLOY_SERVER }}
